name: mealbox_dart_bot
description: An empty Aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  dartis: ^0.5.0
  
  http: ^0.12.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0